default_view: first
views:
  first:
    1:
      text: ğŸ”Œ usb
      command: ls /dev | grep tty.usb
    2:
      text: ğŸ‘¨ğŸ»â€ğŸ’» code
      command: cd ~/code
    3:
      text: ğŸ¤– ap
      command: cd ~/code/ardupilot
    4:
      text: ğŸšœ ap-rov
      command: cd ~/code/ardupilot-rover
    5:
      text: second view
      view: second
    6:
      text: third view
      view: third
  second:
    1:
      text: ğŸ‘ˆ back
      view: first
    2:
      text: current path
      command: pwd
    back: first
  third:
    1:
      text: ğŸ‘ˆ back
      view: first
    2:
      text: ls
      command: ls -la
