default_view: first
views:
  first:
    1:
      text: ğŸ”Œ usb
      command: ls /dev | grep tty.usb
    2:
      text: ğŸ‘¨ğŸ»â€ğŸ’» code
      command: cd ~/code
    3:
      text: ğŸš ap
      command: cd ~/code/ardupilot
    4:
      text: ğŸšœ ap-rov
      command: cd ~/code/ardupilot-rover
    5:
      text: ğŸ¤– ap-sim
      command: Tools/autotest/sim_vehicle.py -v Copter --console --map
    6:
      text: âœˆï¸ proxy
      command: cd ~/code/Lua-script-Align && mavproxy.py --master=/dev/tty.usbmodem14101 --baudrate=115200 --console
    7:
      text: ğŸ“‚ path
      command: pwd
    8:
      text: ğŸ¦š VSC
      command: code .
